development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: keion_development
  pool: 5
  username: root
  password: luo>-*>Mr7esio
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: keion_test
  pool: 5
  username: root
  password: luo>-*>Mr7esio
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: keion_production
  pool: 5
  username: root
  password: luo>-*>Mr7esio
  host: localhost
